apiVersion: v1
kind: Service
metadata:
  labels:
    app: aqua-db
    aqua.component: database
    deployedby: aqua-yaml
  name: aqua-db
  namespace: aqua
spec:
  ports:
    - port: 5432
  selector:
    app: aqua-db
  type: ClusterIP 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: aqua-db
    aqua.component: database
    deployedby: aqua-yaml
  name: aqua-db
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-db
  serviceName: aqua-db
  template:
    metadata:
      labels:
        aqua.component: database
        app: aqua-db
      name: aqua-db
      namespace:    aqua
    spec:
      securityContext:
        runAsUser: 1000
        #readOnlyRootFilesystem: true
        runAsGroup: 1000
        fsGroup: 11433
        #allowPrivilegeEscalation: false
      serviceAccount: aqua-sa
      #restartPolicy: Always
      containers:
      - name: aqua-db
        securityContext:
          privileged: false
        image: registry.aquasec.com/database:2022.4
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: aqua-csp-db-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-db
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            memory: 2Gi
            cpu: 1000m
          limits:
            memory: 8Gi
            cpu: 4000m
      volumes:
      - name: postgres-db
        persistentVolumeClaim:
          claimName: aqua-db-pvc